from enum import Enum


class CreateApiKeyBodyScopesItem(str, Enum):
    API_KEYSMANAGE = "api-keys:manage"
    API_KEYSREAD = "api-keys:read"
    AUDITREAD = "audit:read"
    CMSREAD = "cms:read"
    CMSWRITE = "cms:write"
    COLLECTIONSREAD = "collections:read"
    COLLECTIONSWRITE = "collections:write"
    CONTESTSREAD = "contests:read"
    CONTESTSWRITE = "contests:write"
    CONTRACTSREAD = "contracts:read"
    CONTRACTSWRITE = "contracts:write"
    CONTRIBUTORSREAD = "contributors:read"
    CONTRIBUTORSWRITE = "contributors:write"
    CORRESPONDENCEREAD = "correspondence:read"
    CORRESPONDENCEWRITE = "correspondence:write"
    CSRREAD = "csr:read"
    CSRWRITE = "csr:write"
    EMAIL_TEMPLATESREAD = "email_templates:read"
    EMAIL_TEMPLATESWRITE = "email_templates:write"
    EXTERNAL_SUBMISSIONSREAD = "external-submissions:read"
    EXTERNAL_SUBMISSIONSWRITE = "external-submissions:write"
    FILESREAD = "files:read"
    FILESWRITE = "files:write"
    FORMSREAD = "forms:read"
    FORMSWRITE = "forms:write"
    ISSUESREAD = "issues:read"
    ISSUESWRITE = "issues:write"
    JOURNAL_DIRECTORYREAD = "journal-directory:read"
    MANUSCRIPTSREAD = "manuscripts:read"
    MANUSCRIPTSWRITE = "manuscripts:write"
    NOTIFICATIONSREAD = "notifications:read"
    NOTIFICATIONSWRITE = "notifications:write"
    ORGANIZATIONSREAD = "organizations:read"
    ORGANIZATIONSWRITE = "organizations:write"
    PAYMENTSREAD = "payments:read"
    PAYMENT_TRANSACTIONSREAD = "payment-transactions:read"
    PAYMENT_TRANSACTIONSWRITE = "payment-transactions:write"
    PERIODSREAD = "periods:read"
    PERIODSWRITE = "periods:write"
    PIPELINEREAD = "pipeline:read"
    PIPELINEWRITE = "pipeline:write"
    PORTFOLIOREAD = "portfolio:read"
    PORTFOLIOWRITE = "portfolio:write"
    PUBLICATIONSREAD = "publications:read"
    PUBLICATIONSWRITE = "publications:write"
    READER_FEEDBACKREAD = "reader-feedback:read"
    READER_FEEDBACKWRITE = "reader-feedback:write"
    RIGHTSREAD = "rights:read"
    RIGHTSWRITE = "rights:write"
    SIMSUB_GROUPSREAD = "simsub-groups:read"
    SIMSUB_GROUPSWRITE = "simsub-groups:write"
    SUBMISSIONSREAD = "submissions:read"
    SUBMISSIONSWRITE = "submissions:write"
    USERSREAD = "users:read"
    WEBHOOKSMANAGE = "webhooks:manage"
    WEBHOOKSREAD = "webhooks:read"
    WRITER_PROFILESREAD = "writer-profiles:read"
    WRITER_PROFILESWRITE = "writer-profiles:write"

    def __str__(self) -> str:
        return str(self.value)
