from enum import Enum


class ListAuditEventsResource(str, Enum):
    API_KEY = "api_key"
    AUDIT = "audit"
    AUTH = "auth"
    CMS_CONNECTION = "cms_connection"
    COLLECTION = "collection"
    CONTEST = "contest"
    CONTEST_GROUP = "contest_group"
    CONTRACT = "contract"
    CONTRACT_TEMPLATE = "contract_template"
    CONTRIBUTOR = "contributor"
    CONTRIBUTOR_PUBLICATION = "contributor_publication"
    CORRESPONDENCE = "correspondence"
    CSR = "csr"
    EMAIL = "email"
    EMAIL_TEMPLATE = "email_template"
    EMBED_TOKEN = "embed_token"
    EXTERNAL_SUBMISSION = "external_submission"
    FEDERATION = "federation"
    FILE = "file"
    FORM = "form"
    HUB = "hub"
    INVITATION = "invitation"
    ISSUE = "issue"
    MANUSCRIPT = "manuscript"
    MIGRATION = "migration"
    NOTIFICATION_INBOX = "notification_inbox"
    NOTIFICATION_PREFERENCE = "notification_preference"
    ORGANIZATION = "organization"
    PAYMENT = "payment"
    PAYMENT_TRANSACTION = "payment_transaction"
    PERIOD = "period"
    PIPELINE_ITEM = "pipeline_item"
    PORTFOLIO_ENTRY = "portfolio_entry"
    PUBLICATION = "publication"
    READER_FEEDBACK = "reader_feedback"
    RIGHTS_AGREEMENT = "rights_agreement"
    SIMSUB = "simsub"
    SIMSUB_GROUP = "simsub_group"
    SUBMISSION = "submission"
    TRANSFER = "transfer"
    USER = "user"
    WEBHOOK_DELIVERY = "webhook_delivery"
    WEBHOOK_ENDPOINT = "webhook_endpoint"
    WRITER_PROFILE = "writer_profile"

    def __str__(self) -> str:
        return str(self.value)
