/**
 * Zitadel E2E provisioning script.
 *
 * Automates Zitadel setup for OIDC E2E tests:
 * 1. Wait for Zitadel health
 * 2. Read machine-user PAT (created by start-from-init via FIRSTINSTANCE env vars)
 * 3. Create/find project + OIDC app (with JWT access tokens)
 * 4. Create/find test user
 * 5. Insert user into Colophony DB + add org membership
 * 6. Write config to apps/web/e2e/.zitadel-e2e-config.json
 *
 * Idempotent: checks for existing resources before creating.
 *
 * Usage:
 *   tsx scripts/setup-zitadel-e2e.ts
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { Pool } from "pg";

const ZITADEL_URL = process.env.ZITADEL_URL || "http://localhost:8080";
const DATABASE_URL =
  process.env.DATABASE_URL ||
  "postgresql://colophony:password@localhost:5432/colophony";

// Path where docker-compose Zitadel writes the IAM_OWNER PAT on first init
const PAT_FILE_PATH =
  process.env.ZITADEL_PAT_PATH ||
  resolve(__dirname, "../.docker/zitadel/machinekey/admin.pat");

const E2E_PROJECT_NAME = "colophony-e2e";
const E2E_APP_NAME = "colophony-e2e-web";
const E2E_WEB_PORT = process.env.E2E_WEB_PORT || "3010";
const E2E_REDIRECT_URI = `http://localhost:${E2E_WEB_PORT}/auth/callback`;
const E2E_POST_LOGOUT_URI = `http://localhost:${E2E_WEB_PORT}`;

// Also allow port 3000 (dev server) so the same Zitadel app works for manual QA
const DEV_REDIRECT_URI = "http://localhost:3000/auth/callback";
const DEV_POST_LOGOUT_URI = "http://localhost:3000";

const TEST_USER_EMAIL = "e2e-test@colophony.dev";
const TEST_USER_PASSWORD = "E2eTestPassword1!";
const TEST_USER_FIRST = "E2E";
const TEST_USER_LAST = "TestUser";

const CONFIG_OUTPUT = resolve(
  __dirname,
  "../apps/web/e2e/.zitadel-e2e-config.json",
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function waitForHealth(
  maxRetries = 30,
  intervalMs = 2000,
): Promise<void> {
  console.log(`Waiting for Zitadel at ${ZITADEL_URL}...`);
  for (let i = 0; i < maxRetries; i++) {
    try {
      const res = await fetch(`${ZITADEL_URL}/debug/healthz`);
      if (res.ok) {
        console.log("Zitadel is healthy.");
        return;
      }
    } catch {
      // Not ready yet
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error(`Zitadel not healthy after ${maxRetries * intervalMs}ms`);
}

/**
 * Read the IAM_OWNER PAT from the file generated by Zitadel's start-from-init.
 *
 * The docker-compose Zitadel service is configured with ZITADEL_FIRSTINSTANCE_PATPATH
 * which writes a PAT for a machine user with IAM_OWNER role on first initialization.
 * This PAT is valid for Management API and Admin API calls.
 */
function getAdminToken(): string {
  if (!existsSync(PAT_FILE_PATH)) {
    throw new Error(
      `Zitadel admin PAT not found at ${PAT_FILE_PATH}.\n` +
        "Ensure Zitadel was started with `docker compose --profile auth up -d` " +
        "and the ZITADEL_FIRSTINSTANCE_PATPATH env var is configured.\n" +
        "If Zitadel was previously initialized without the machine user config, " +
        "run `docker compose down -v` and restart to reinitialize.",
    );
  }

  const pat = readFileSync(PAT_FILE_PATH, "utf-8").trim();
  if (!pat) {
    throw new Error(`Zitadel admin PAT file at ${PAT_FILE_PATH} is empty.`);
  }

  console.log("Loaded admin PAT from file.");
  return pat;
}

interface ApiResponse<T> {
  ok: boolean;
  status: number;
  data: T;
}

async function zitadelApi<T>(
  token: string,
  path: string,
  method: string = "POST",
  body?: unknown,
): Promise<ApiResponse<T>> {
  const res = await fetch(`${ZITADEL_URL}${path}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const data = (await res.json().catch(() => ({}))) as T;
  return { ok: res.ok, status: res.status, data };
}

// ---------------------------------------------------------------------------
// Provisioning
// ---------------------------------------------------------------------------

async function findOrCreateProject(token: string): Promise<string> {
  // Search for existing project
  const search = await zitadelApi<{
    result?: Array<{ id: string; name: string }>;
  }>(token, "/management/v1/projects/_search", "POST", {
    queries: [
      {
        nameQuery: {
          name: E2E_PROJECT_NAME,
          method: "TEXT_QUERY_METHOD_EQUALS",
        },
      },
    ],
  });

  if (search.ok && search.data.result?.length) {
    console.log(`Found existing project: ${search.data.result[0].id}`);
    return search.data.result[0].id;
  }

  // Create project
  const create = await zitadelApi<{ id: string }>(
    token,
    "/management/v1/projects",
    "POST",
    { name: E2E_PROJECT_NAME },
  );

  if (!create.ok) {
    throw new Error(`Failed to create project: ${JSON.stringify(create.data)}`);
  }

  console.log(`Created project: ${create.data.id}`);
  return create.data.id;
}

async function findOrCreateOidcApp(
  token: string,
  projectId: string,
): Promise<{ appId: string; clientId: string }> {
  // Search for existing app
  const search = await zitadelApi<{
    result?: Array<{
      id: string;
      name: string;
      oidcConfig?: { clientId: string };
    }>;
  }>(token, `/management/v1/projects/${projectId}/apps/_search`, "POST", {});

  const existing = search.data.result?.find((a) => a.name === E2E_APP_NAME);
  if (existing?.oidcConfig) {
    console.log(`Found existing OIDC app: ${existing.oidcConfig.clientId}`);
    // Ensure redirect URIs include both E2E and dev ports
    await zitadelApi(
      token,
      `/management/v1/projects/${projectId}/apps/${existing.id}/oidc`,
      "PUT",
      {
        redirectUris: [E2E_REDIRECT_URI, DEV_REDIRECT_URI],
        postLogoutRedirectUris: [E2E_POST_LOGOUT_URI, DEV_POST_LOGOUT_URI],
        responseTypes: ["OIDC_RESPONSE_TYPE_CODE"],
        grantTypes: ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
        appType: "OIDC_APP_TYPE_USER_AGENT",
        authMethodType: "OIDC_AUTH_METHOD_TYPE_NONE",
        accessTokenType: "OIDC_TOKEN_TYPE_JWT",
        accessTokenRoleAssertion: true,
        devMode: true,
      },
    );
    console.log("Updated OIDC app redirect URIs.");
    return { appId: existing.id, clientId: existing.oidcConfig.clientId };
  }

  // Create OIDC app with JWT access tokens (required for JWKS verification)
  const create = await zitadelApi<{
    appId: string;
    clientId: string;
  }>(token, `/management/v1/projects/${projectId}/apps/oidc`, "POST", {
    name: E2E_APP_NAME,
    redirectUris: [E2E_REDIRECT_URI, DEV_REDIRECT_URI],
    postLogoutRedirectUris: [E2E_POST_LOGOUT_URI, DEV_POST_LOGOUT_URI],
    responseTypes: ["OIDC_RESPONSE_TYPE_CODE"],
    grantTypes: ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
    appType: "OIDC_APP_TYPE_USER_AGENT",
    authMethodType: "OIDC_AUTH_METHOD_TYPE_NONE", // PKCE (no client secret)
    accessTokenType: "OIDC_TOKEN_TYPE_JWT", // JWT tokens for JWKS verification
    accessTokenRoleAssertion: true, // Include roles in token
    devMode: true, // Allow http redirects in dev
  });

  if (!create.ok) {
    throw new Error(
      `Failed to create OIDC app: ${JSON.stringify(create.data)}`,
    );
  }

  console.log(`Created OIDC app: ${create.data.clientId}`);
  return { appId: create.data.appId, clientId: create.data.clientId };
}

async function findOrCreateUser(token: string): Promise<string> {
  // Search for existing user
  const search = await zitadelApi<{
    result?: Array<{ userId: string }>;
  }>(token, "/v2/users", "POST", {
    queries: [
      {
        emailQuery: {
          emailAddress: TEST_USER_EMAIL,
          method: "TEXT_QUERY_METHOD_EQUALS",
        },
      },
    ],
  });

  if (search.ok && search.data.result?.length) {
    console.log(`Found existing user: ${search.data.result[0].userId}`);
    return search.data.result[0].userId;
  }

  // Create human user
  const create = await zitadelApi<{ userId: string }>(
    token,
    "/v2/users/human",
    "POST",
    {
      username: TEST_USER_EMAIL,
      profile: {
        givenName: TEST_USER_FIRST,
        familyName: TEST_USER_LAST,
      },
      email: {
        email: TEST_USER_EMAIL,
        isVerified: true,
      },
      password: {
        password: TEST_USER_PASSWORD,
        changeRequired: false,
      },
    },
  );

  if (!create.ok) {
    throw new Error(`Failed to create user: ${JSON.stringify(create.data)}`);
  }

  console.log(`Created user: ${create.data.userId}`);
  return create.data.userId;
}

async function ensureColophonyUser(
  zitadelUserId: string,
): Promise<{ userId: string; orgId: string }> {
  const pool = new Pool({ connectionString: DATABASE_URL, max: 2 });

  try {
    // Check if user already exists (by Zitadel ID or email)
    const existing = await pool.query<{ id: string; zitadel_user_id: string }>(
      "SELECT id, zitadel_user_id FROM users WHERE zitadel_user_id = $1 OR email = $2 LIMIT 1",
      [zitadelUserId, TEST_USER_EMAIL],
    );

    let userId: string;
    if (existing.rows.length > 0) {
      userId = existing.rows[0].id;
      // Update Zitadel user ID if it changed (e.g., Zitadel DB was reinitialized)
      if (existing.rows[0].zitadel_user_id !== zitadelUserId) {
        await pool.query(
          "UPDATE users SET zitadel_user_id = $1 WHERE id = $2",
          [zitadelUserId, userId],
        );
        console.log(`Updated Zitadel user ID for existing user: ${userId}`);
      } else {
        console.log(`Found existing Colophony user: ${userId}`);
      }
    } else {
      const insert = await pool.query<{ id: string }>(
        "INSERT INTO users (email, zitadel_user_id) VALUES ($1, $2) RETURNING id",
        [TEST_USER_EMAIL, zitadelUserId],
      );
      userId = insert.rows[0].id;
      console.log(`Created Colophony user: ${userId}`);
    }

    // Find or use the seed org
    const orgResult = await pool.query<{ id: string }>(
      "SELECT id FROM organizations WHERE slug = 'quarterly-review' LIMIT 1",
    );

    if (orgResult.rows.length === 0) {
      throw new Error(
        'Seed org "quarterly-review" not found. Run `pnpm db:seed` first.',
      );
    }

    const orgId = orgResult.rows[0].id;

    // Add membership if not exists
    const memberExists = await pool.query(
      "SELECT 1 FROM organization_members WHERE organization_id = $1 AND user_id = $2",
      [orgId, userId],
    );

    if (memberExists.rows.length === 0) {
      await pool.query(
        "INSERT INTO organization_members (organization_id, user_id, role) VALUES ($1, $2, $3)",
        [orgId, userId, "ADMIN"],
      );
      console.log(`Added user to org ${orgId} as ADMIN`);
    }

    return { userId, orgId };
  } finally {
    await pool.end();
  }
}

async function disableMfaRequirement(token: string): Promise<void> {
  // Update the default login policy to not force MFA and allow skipping MFA setup
  const res = await zitadelApi(token, "/admin/v1/policies/login", "PUT", {
    allowUsernamePassword: true,
    allowRegister: false,
    allowExternalIdp: false,
    forceMfa: false,
    forceMfaLocalOnly: false,
    passwordlessType: "PASSWORDLESS_TYPE_NOT_ALLOWED",
    allowDomainDiscovery: false,
    passwordCheckLifetime: "864000s",
    externalLoginCheckLifetime: "864000s",
    mfaInitSkipLifetime: "2592000s",
    secondFactorCheckLifetime: "64800s",
    multiFactorCheckLifetime: "43200s",
  });

  if (!res.ok) {
    console.warn(
      `Warning: Failed to update login policy: ${JSON.stringify(res.data)}`,
    );
  } else {
    console.log("Disabled MFA requirement in login policy.");
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log("=== Zitadel E2E Setup ===\n");

  // 1. Wait for Zitadel
  await waitForHealth();

  // 2. Get admin token (PAT from start-from-init machine user)
  console.log("\nReading admin PAT...");
  const token = getAdminToken();

  // 3. Disable MFA requirement for E2E tests
  console.log("\nConfiguring login policy...");
  await disableMfaRequirement(token);

  // 4. Create project
  console.log("\nSetting up project...");
  const projectId = await findOrCreateProject(token);

  // 5. Create OIDC app
  console.log("\nSetting up OIDC app...");
  const { clientId } = await findOrCreateOidcApp(token, projectId);

  // 6. Create test user in Zitadel
  console.log("\nSetting up test user...");
  const zitadelUserId = await findOrCreateUser(token);

  // 7. Insert into Colophony DB
  console.log("\nSyncing to Colophony DB...");
  const { userId, orgId } = await ensureColophonyUser(zitadelUserId);

  // 8. Write config file
  // projectId is used as ZITADEL_CLIENT_ID for the API's audience validation,
  // since Zitadel JWT access tokens put the project ID in the `aud` claim.
  const config = {
    authority: ZITADEL_URL,
    clientId,
    projectId,
    testUserEmail: TEST_USER_EMAIL,
    testUserPassword: TEST_USER_PASSWORD,
    testUserId: userId,
    testOrgId: orgId,
    zitadelUserId,
  };

  writeFileSync(CONFIG_OUTPUT, JSON.stringify(config, null, 2) + "\n");
  console.log(`\nConfig written to: ${CONFIG_OUTPUT}`);
  console.log("\n=== Setup complete ===");
}

main().catch((err) => {
  console.error("\nSetup failed:", err);
  process.exit(1);
});
