/**
 * Shared Zitadel provisioning helpers.
 *
 * Used by both setup-zitadel-e2e.ts and setup-zitadel-dev.ts.
 * Idempotent: checks for existing resources before creating.
 */

import { existsSync, readFileSync } from "fs";
import { resolve } from "path";
import { Pool } from "pg";

// ---------------------------------------------------------------------------
// Config defaults (can be overridden by callers or env vars)
// ---------------------------------------------------------------------------

export const ZITADEL_URL = process.env.ZITADEL_URL || "http://localhost:8080";
export const DATABASE_URL =
  process.env.DATABASE_URL ||
  "postgresql://colophony:password@localhost:5432/colophony";

const PAT_FILE_PATH =
  process.env.ZITADEL_PAT_PATH ||
  resolve(__dirname, "../.docker/zitadel/machinekey/admin.pat");

export const TEST_USER_EMAIL = "e2e-test@colophony.dev";
export const TEST_USER_PASSWORD = "E2eTestPassword1!";
export const TEST_USER_FIRST = "E2E";
export const TEST_USER_LAST = "TestUser";

// ---------------------------------------------------------------------------
// HTTP helpers
// ---------------------------------------------------------------------------

export interface ApiResponse<T> {
  ok: boolean;
  status: number;
  data: T;
}

export async function waitForHealth(
  maxRetries = 30,
  intervalMs = 2000,
): Promise<void> {
  console.log(`Waiting for Zitadel at ${ZITADEL_URL}...`);
  for (let i = 0; i < maxRetries; i++) {
    try {
      const res = await fetch(`${ZITADEL_URL}/debug/healthz`);
      if (res.ok) {
        console.log("Zitadel is healthy.");
        return;
      }
    } catch {
      // Not ready yet
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error(`Zitadel not healthy after ${maxRetries * intervalMs}ms`);
}

/**
 * Read the IAM_OWNER PAT from the file generated by Zitadel's start-from-init.
 *
 * The docker-compose Zitadel service is configured with ZITADEL_FIRSTINSTANCE_PATPATH
 * which writes a PAT for a machine user with IAM_OWNER role on first initialization.
 * This PAT is valid for Management API and Admin API calls.
 */
export function getAdminToken(): string {
  if (!existsSync(PAT_FILE_PATH)) {
    throw new Error(
      `Zitadel admin PAT not found at ${PAT_FILE_PATH}.\n` +
        "Ensure Zitadel was started with `docker compose --profile auth up -d` " +
        "and the ZITADEL_FIRSTINSTANCE_PATPATH env var is configured.\n" +
        "If Zitadel was previously initialized without the machine user config, " +
        "run `docker compose down -v` and restart to reinitialize.",
    );
  }

  const pat = readFileSync(PAT_FILE_PATH, "utf-8").trim();
  if (!pat) {
    throw new Error(`Zitadel admin PAT file at ${PAT_FILE_PATH} is empty.`);
  }

  console.log("Loaded admin PAT from file.");
  return pat;
}

export async function zitadelApi<T>(
  token: string,
  path: string,
  method: string = "POST",
  body?: unknown,
  baseUrl: string = ZITADEL_URL,
): Promise<ApiResponse<T>> {
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const data = (await res.json().catch(() => ({}))) as T;
  return { ok: res.ok, status: res.status, data };
}

// ---------------------------------------------------------------------------
// Provisioning helpers
// ---------------------------------------------------------------------------

export async function findOrCreateProject(
  token: string,
  projectName: string,
): Promise<string> {
  const search = await zitadelApi<{
    result?: Array<{ id: string; name: string }>;
  }>(token, "/management/v1/projects/_search", "POST", {
    queries: [
      {
        nameQuery: {
          name: projectName,
          method: "TEXT_QUERY_METHOD_EQUALS",
        },
      },
    ],
  });

  if (search.ok && search.data.result?.length) {
    console.log(`Found existing project: ${search.data.result[0].id}`);
    return search.data.result[0].id;
  }

  const create = await zitadelApi<{ id: string }>(
    token,
    "/management/v1/projects",
    "POST",
    { name: projectName },
  );

  if (!create.ok) {
    throw new Error(`Failed to create project: ${JSON.stringify(create.data)}`);
  }

  console.log(`Created project: ${create.data.id}`);
  return create.data.id;
}

export async function findOrCreateOidcApp(
  token: string,
  projectId: string,
  appName: string,
  redirectUris: string[],
  postLogoutUris: string[],
): Promise<{ appId: string; clientId: string }> {
  const search = await zitadelApi<{
    result?: Array<{
      id: string;
      name: string;
      oidcConfig?: { clientId: string };
    }>;
  }>(token, `/management/v1/projects/${projectId}/apps/_search`, "POST", {});

  const existing = search.data.result?.find((a) => a.name === appName);
  if (existing?.oidcConfig) {
    console.log(`Found existing OIDC app: ${existing.oidcConfig.clientId}`);
    // Ensure redirect URIs are up to date
    await zitadelApi(
      token,
      `/management/v1/projects/${projectId}/apps/${existing.id}/oidc`,
      "PUT",
      {
        redirectUris,
        postLogoutRedirectUris: postLogoutUris,
        responseTypes: ["OIDC_RESPONSE_TYPE_CODE"],
        grantTypes: ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
        appType: "OIDC_APP_TYPE_USER_AGENT",
        authMethodType: "OIDC_AUTH_METHOD_TYPE_NONE",
        accessTokenType: "OIDC_TOKEN_TYPE_JWT",
        accessTokenRoleAssertion: true,
        devMode: true,
      },
    );
    console.log("Updated OIDC app redirect URIs.");
    return { appId: existing.id, clientId: existing.oidcConfig.clientId };
  }

  const create = await zitadelApi<{
    appId: string;
    clientId: string;
  }>(token, `/management/v1/projects/${projectId}/apps/oidc`, "POST", {
    name: appName,
    redirectUris,
    postLogoutRedirectUris: postLogoutUris,
    responseTypes: ["OIDC_RESPONSE_TYPE_CODE"],
    grantTypes: ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
    appType: "OIDC_APP_TYPE_USER_AGENT",
    authMethodType: "OIDC_AUTH_METHOD_TYPE_NONE", // PKCE (no client secret)
    accessTokenType: "OIDC_TOKEN_TYPE_JWT", // JWT tokens for JWKS verification
    accessTokenRoleAssertion: true, // Include roles in token
    devMode: true, // Allow http redirects in dev
  });

  if (!create.ok) {
    throw new Error(
      `Failed to create OIDC app: ${JSON.stringify(create.data)}`,
    );
  }

  console.log(`Created OIDC app: ${create.data.clientId}`);
  return { appId: create.data.appId, clientId: create.data.clientId };
}

export async function findOrCreateUser(
  token: string,
  email: string,
  password: string,
  firstName: string,
  lastName: string,
): Promise<string> {
  const search = await zitadelApi<{
    result?: Array<{ userId: string }>;
  }>(token, "/v2/users", "POST", {
    queries: [
      {
        emailQuery: {
          emailAddress: email,
          method: "TEXT_QUERY_METHOD_EQUALS",
        },
      },
    ],
  });

  if (search.ok && search.data.result?.length) {
    console.log(`Found existing user: ${search.data.result[0].userId}`);
    return search.data.result[0].userId;
  }

  const create = await zitadelApi<{ userId: string }>(
    token,
    "/v2/users/human",
    "POST",
    {
      username: email,
      profile: {
        givenName: firstName,
        familyName: lastName,
      },
      email: {
        email,
        isVerified: true,
      },
      password: {
        password,
        changeRequired: false,
      },
    },
  );

  if (!create.ok) {
    throw new Error(`Failed to create user: ${JSON.stringify(create.data)}`);
  }

  console.log(`Created user: ${create.data.userId}`);
  return create.data.userId;
}

export async function ensureColophonyUser(
  zitadelUserId: string,
  userEmail: string,
  orgSlug: string,
): Promise<{ userId: string; orgId: string }> {
  const pool = new Pool({ connectionString: DATABASE_URL, max: 2 });

  try {
    const existing = await pool.query<{ id: string; zitadel_user_id: string }>(
      "SELECT id, zitadel_user_id FROM users WHERE zitadel_user_id = $1 OR email = $2 LIMIT 1",
      [zitadelUserId, userEmail],
    );

    let userId: string;
    if (existing.rows.length > 0) {
      userId = existing.rows[0].id;
      if (existing.rows[0].zitadel_user_id !== zitadelUserId) {
        await pool.query(
          "UPDATE users SET zitadel_user_id = $1 WHERE id = $2",
          [zitadelUserId, userId],
        );
        console.log(`Updated Zitadel user ID for existing user: ${userId}`);
      } else {
        console.log(`Found existing Colophony user: ${userId}`);
      }
    } else {
      const insert = await pool.query<{ id: string }>(
        "INSERT INTO users (email, zitadel_user_id) VALUES ($1, $2) RETURNING id",
        [userEmail, zitadelUserId],
      );
      userId = insert.rows[0].id;
      console.log(`Created Colophony user: ${userId}`);
    }

    const orgResult = await pool.query<{ id: string }>(
      "SELECT id FROM organizations WHERE slug = $1 LIMIT 1",
      [orgSlug],
    );

    if (orgResult.rows.length === 0) {
      throw new Error(
        `Seed org "${orgSlug}" not found. Run \`pnpm db:seed\` first.`,
      );
    }

    const orgId = orgResult.rows[0].id;

    const memberExists = await pool.query(
      "SELECT 1 FROM organization_members WHERE organization_id = $1 AND user_id = $2",
      [orgId, userId],
    );

    if (memberExists.rows.length === 0) {
      await pool.query(
        "INSERT INTO organization_members (organization_id, user_id, roles) VALUES ($1, $2, $3)",
        [orgId, userId, ["ADMIN"]],
      );
      console.log(`Added user to org ${orgId} as ADMIN`);
    }

    return { userId, orgId };
  } finally {
    await pool.end();
  }
}

// ---------------------------------------------------------------------------
// Webhook target + execution helpers (Zitadel Actions v2)
// ---------------------------------------------------------------------------

/**
 * Zitadel event groups to set executions for.
 *
 * The "user" group covers all user lifecycle events that the webhook handler
 * supports: user.human.added, user.human.profile.changed, user.deactivated,
 * user.reactivated, user.removed, user.human.email.verified.
 *
 * Note: Zitadel execution condition event names differ from the `event_type`
 * field in the webhook payload. The webhook handler's EVENT_TYPE_ALIASES table
 * maps the payload event names to internal names. Unknown events are logged
 * and skipped.
 */
export const WEBHOOK_EVENT_GROUPS = ["user"] as const;

/**
 * Individual event types the webhook handler supports (for diagnostics).
 * These are the `event_type` values in the webhook payload — note that
 * execution condition names may differ from these payload names.
 */
export const WEBHOOK_EVENT_TYPES = [
  "user.human.added",
  "user.human.changed",
  "user.human.profile.changed",
  "user.human.email.verified",
  "user.deactivated",
  "user.reactivated",
  "user.removed",
] as const;

/**
 * Find or create a Zitadel Actions v2 webhook target.
 *
 * When the target is created, Zitadel returns a one-time `signingKey` (HMAC
 * secret for ZITADEL-Signature verification). When the target already exists,
 * the signing key is NOT returned — callers must handle this case.
 */
export async function findOrCreateTarget(
  token: string,
  name: string,
  url: string,
  timeout: string = "10s",
  baseUrl?: string,
): Promise<{ targetId: string; signingKey: string | null }> {
  // Search for existing target by name
  const search = await zitadelApi<{
    targets?: Array<{ id: string; name: string; signingKey?: string }>;
  }>(
    token,
    "/v2/actions/targets/search",
    "POST",
    {
      queries: [
        {
          targetNameQuery: {
            targetName: name,
            method: "TEXT_QUERY_METHOD_EQUALS",
          },
        },
      ],
    },
    baseUrl,
  );

  if (search.ok && search.data.targets?.length) {
    // Client-side exact match — Zitadel's targetNameQuery may not filter exactly
    const existing = search.data.targets.find((t) => t.name === name);
    if (existing) {
      console.log(`Found existing webhook target: ${existing.id}`);
      // Zitadel returns signingKey on search too, but it may not always be present
      return { targetId: existing.id, signingKey: existing.signingKey ?? null };
    }
  }

  // Create new target — Zitadel Actions v2 uses snake_case field names
  const create = await zitadelApi<{
    id: string;
    signingKey: string;
  }>(
    token,
    "/v2/actions/targets",
    "POST",
    {
      name,
      rest_webhook: { interrupt_on_error: false },
      endpoint: url,
      timeout,
    },
    baseUrl,
  );

  if (!create.ok) {
    throw new Error(
      `Failed to create webhook target: ${JSON.stringify(create.data)}`,
    );
  }

  console.log(`Created webhook target: ${create.data.id}`);
  return { targetId: create.data.id, signingKey: create.data.signingKey };
}

/**
 * Set a Zitadel execution that fires a target on an event group.
 *
 * Merges with existing targets: reads the current execution first, then
 * PUTs the union of existing + new target IDs. This allows dev and E2E
 * targets to coexist on the same Zitadel instance.
 */
export async function setGroupExecution(
  token: string,
  group: string,
  targetId: string,
  baseUrl?: string,
): Promise<void> {
  // Read existing execution targets for this group
  const search = await zitadelApi<{
    executions?: Array<{
      condition: { event?: { group?: string } };
      targets?: string[];
    }>;
  }>(
    token,
    "/v2/actions/executions/search",
    "POST",
    {
      queries: [
        {
          eventConditionQuery: {
            group,
          },
        },
      ],
    },
    baseUrl,
  );

  const existingTargets: string[] = [];
  if (search.ok && search.data.executions?.length) {
    const existing = search.data.executions[0];
    if (existing.targets) {
      existingTargets.push(...existing.targets);
    }
  }

  // Merge: add new target if not already present
  const mergedTargets = existingTargets.includes(targetId)
    ? existingTargets
    : [...existingTargets, targetId];

  const res = await zitadelApi(
    token,
    "/v2/actions/executions",
    "PUT",
    {
      condition: {
        event: {
          group,
        },
      },
      targets: mergedTargets,
    },
    baseUrl,
  );

  if (!res.ok) {
    throw new Error(
      `Failed to set execution for group ${group}: ${JSON.stringify(res.data)}`,
    );
  }

  if (mergedTargets.length > 1) {
    console.log(
      `  Execution set: group "${group}" → ${mergedTargets.length} targets (merged)`,
    );
  } else {
    console.log(`  Execution set: group "${group}" → target ${targetId}`);
  }
}

/**
 * Set up webhook target and executions for all user lifecycle events.
 * Returns the signing key if the target was newly created, null if it existed.
 */
export async function setupWebhookExecutions(
  token: string,
  targetName: string,
  webhookUrl: string,
): Promise<string | null> {
  console.log(`\nSetting up webhook target: ${targetName}`);
  console.log(`  URL: ${webhookUrl}`);

  const { targetId, signingKey } = await findOrCreateTarget(
    token,
    targetName,
    webhookUrl,
  );

  console.log("\nConfiguring executions for user lifecycle events...");
  for (const group of WEBHOOK_EVENT_GROUPS) {
    await setGroupExecution(token, group, targetId);
  }

  console.log("\nWebhook executions configured.");
  return signingKey;
}

export async function disableMfaRequirement(token: string): Promise<void> {
  const res = await zitadelApi(token, "/admin/v1/policies/login", "PUT", {
    allowUsernamePassword: true,
    allowRegister: false,
    allowExternalIdp: false,
    forceMfa: false,
    forceMfaLocalOnly: false,
    passwordlessType: "PASSWORDLESS_TYPE_NOT_ALLOWED",
    allowDomainDiscovery: false,
    passwordCheckLifetime: "864000s",
    externalLoginCheckLifetime: "864000s",
    mfaInitSkipLifetime: "2592000s",
    secondFactorCheckLifetime: "64800s",
    multiFactorCheckLifetime: "43200s",
  });

  if (!res.ok) {
    console.warn(
      `Warning: Failed to update login policy: ${JSON.stringify(res.data)}`,
    );
  } else {
    console.log("Disabled MFA requirement in login policy.");
  }
}
